/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":ArtMap-api"))
    compileOnly ("org.spigotmc:spigot-api:1.20.1-R0.1-SNAPSHOT")
    compileOnly ("com.mojang:authlib:5.0.47")
}

description = "Spigot_1_20_@"
