/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

pluginManagement {
    // Include 'plugins build' to define convention plugins.
    includeBuild("build-logic")

    pluginManagement {
        repositories {
            mavenCentral()
            gradlePluginPortal()
            maven("https://papermc.io/repo/repository/maven-releases/")
        }
    }
}

plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.9.0"
}


rootProject.name = "ArtMap-parent"
include(":GriefPrevention")
include(":DataTables")
include(":BentoBox")
include(":MarriageMaster")
include(":USkyBlock")
include(":WorldGuard")
include(":Spigot_1_21_4")
include(":ArtMap")
include(":Spigot_1_16")
include(":PlotSquared7")
include(":Spigot_1_14")
include(":Paper_1_21_5")
include(":Paper_1_21_6")
include(":Paper_1_21_7")
include(":Paper_1_21_8")
include(":Paper_1_21_9")
include(":PlotSquared5")
include(":Towny")
include(":RedProtect")
include(":CMI")
include(":Spigot_1_20_2")
include(":Factions")
include(":GriefDefender")
include(":Spigot_1_18")
include(":Essentials")
include(":Spigot_1_13")
include(":PlotSquared6")
include(":PlotSquared4")
include(":ASkyBlock")
include(":Residence")
include(":ArtMap-api")
project(":GriefPrevention").projectDir = file("compatibility/GriefPrevention")
project(":BentoBox").projectDir = file("compatibility/BentoBox")
project(":MarriageMaster").projectDir = file("compatibility/MarriageMaster")
project(":USkyBlock").projectDir = file("compatibility/USkyBlock")
project(":WorldGuard").projectDir = file("compatibility/WorldGuard")
project(":Spigot_1_21_4").projectDir = file("compatibility/Spigot_1_21_4")
project(":ArtMap").projectDir = file("plugin")
project(":Spigot_1_16").projectDir = file("compatibility/Spigot_1_16")
project(":PlotSquared7").projectDir = file("compatibility/PlotSquared7")
project(":Spigot_1_14").projectDir = file("compatibility/Spigot_1_14")
project(":Paper_1_21_5").projectDir = file("compatibility/Paper_1_21_5")
project(":Paper_1_21_6").projectDir = file("compatibility/Paper_1_21_6")
project(":Paper_1_21_7").projectDir = file("compatibility/Paper_1_21_7")
project(":Paper_1_21_8").projectDir = file("compatibility/Paper_1_21_8")
project(":Paper_1_21_9").projectDir = file("compatibility/Paper_1_21_9")
project(":PlotSquared5").projectDir = file("compatibility/PlotSquared5")
project(":Towny").projectDir = file("compatibility/Towny")
project(":RedProtect").projectDir = file("compatibility/RedProtect")
project(":CMI").projectDir = file("compatibility/CMI")
project(":Spigot_1_20_2").projectDir = file("compatibility/Spigot_1_20_2")
project(":Factions").projectDir = file("compatibility/Factions")
project(":GriefDefender").projectDir = file("compatibility/GriefDefender")
project(":Spigot_1_18").projectDir = file("compatibility/Spigot_1_18")
project(":Essentials").projectDir = file("compatibility/Essentials")
project(":Spigot_1_13").projectDir = file("compatibility/Spigot_1_13")
project(":PlotSquared6").projectDir = file("compatibility/PlotSquared6")
project(":PlotSquared4").projectDir = file("compatibility/PlotSquared4")
project(":ASkyBlock").projectDir = file("compatibility/ASkyBlock")
project(":Residence").projectDir = file("compatibility/Residence")
project(":ArtMap-api").projectDir = file("api")
