/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":ArtMap-api"))
    compileOnly ("org.spigotmc:spigot-api:1.14.4-R0.1-SNAPSHOT")
    compileOnly ("com.github.rlf:uSkyBlock-API:2.6.4")
}

description = "U SkyBlock4"
