/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":ArtMap-api"))
    api ("net.ess3:EssentialsX:2.18.2")
    compileOnly ("org.spigotmc:spigot-api:1.14.4-R0.1-SNAPSHOT")
}

description = "Essentials"
