/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-conventions")
    java
    id("com.gradleup.shadow") version "9.2.2"
}

dependencies {
    api(project(":ArtMap-api"))
    api(project(":DataTables"))
    api("net.wesjd:anvilgui:1.10.9-SNAPSHOT")
    api(project(":Spigot_1_13"))
    api(project(":Spigot_1_14"))
    api(project(":Spigot_1_16"))
    api(project(":Spigot_1_18"))
    api(project(":Spigot_1_20_2"))
    api(project(":Spigot_1_21_4"))
    api(project(":Paper_1_21_5"))
    api(project(":Paper_1_21_6"))
    api(project(":Paper_1_21_7"))
    api(project(":Paper_1_21_8"))
    api(project(":Paper_1_21_9"))
    api(project(":ASkyBlock"))
    api(project(":BentoBox"))
    api(project(":CMI"))
    api(project(":Essentials"))
    api(project(":Factions"))
    api(project(":GriefDefender"))
    api(project(":GriefPrevention"))
    api(project(":MarriageMaster"))
    api(project(":PlotSquared4"))
    api(project(":PlotSquared5"))
    api(project(":PlotSquared6"))
    api(project(":PlotSquared7"))
    api(project(":RedProtect"))
    api(project(":Residence"))
    api(project(":Towny"))
    api(project(":USkyBlock"))
    api(project(":WorldGuard"))

    testImplementation("com.github.seeseemelk:MockBukkit-v1.21:3.133.2")
    testImplementation("org.xerial:sqlite-jdbc:3.47.0.0")
    testImplementation("junit:junit:4.13.2")
    testImplementation("org.mockito:mockito-core:5.14.2")
    testImplementation("net.bytebuddy:byte-buddy:1.15.10")

    compileOnly("io.papermc.paper:paper-api:1.17-R0.1-SNAPSHOT")
    compileOnly("com.google.code.gson:gson:2.11.0")
    compileOnly("io.netty:netty-all:4.1.66.Final")
    compileOnly("com.mojang:accounts-client:1.3.0")
    compileOnly("com.mojang:authlib:1.5.25")
    compileOnly("net.dmulloy2:ProtocolLib:5.4.0")
}

tasks.shadowJar {

    dependsOn(tasks.processResources)
    from(tasks.processResources.get().outputs)

    archiveFileName.set("${project.name}-${project.version}-shaded.jar")
    dependencies {
        include(dependency("com.github.Fupery:.*"))
        include(dependency("me.Fupery:DataTables:.*"))
        include(dependency("net.wesjd:anvilgui:.*"))
        include(dependency("com.gitlab.blockstack:.*"))

        exclude(dependency("org.spigotmc:.*"))
        exclude(dependency("org.bukkit:.*"))
    }
    relocate("net.wesjd.anvilgui", "me.fupery.shade")
}




description = "ArtMap"
