/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":ArtMap-api"))
    compileOnly ("org.spigotmc:spigot-api:1.14.4-R0.1-SNAPSHOT")
    compileOnly ("com.plotsquared:PlotSquared-Core:6.11.1")
    compileOnly ("com.intellectualsites.plotsquared:plotsquared-bukkit:7.0.0")
    compileOnly ("com.sk89q.worldedit:worldedit-bukkit:7.2.2")
}

description = "Plot Squared 6"
