/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-conventions")
    id("io.papermc.paperweight.userdev") version "2.0.0-beta.18"
}

paperweight.reobfArtifactConfiguration = io.papermc.paperweight.userdev.ReobfArtifactConfiguration.MOJANG_PRODUCTION
java.toolchain.languageVersion.set(JavaLanguageVersion.of(21))

repositories {
    maven {
        url = uri("https://repo.papermc.io/repository/maven-public/")
    }
}

dependencies {
    api(project(":ArtMap-api"))
    implementation("net.kyori:adventure-text-serializer-ansi:4.24.0")
    compileOnly ("io.papermc.paper:paper-api:1.21.7-R0.1-SNAPSHOT")
    paperweight.paperDevBundle("1.21.7-R0.1-SNAPSHOT")
    compileOnly ("com.mojang:authlib:5.0.47")
}

description = "Paper_1_21_7"
