/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    compileOnly("io.papermc.paper:paper-api:1.17-R0.1-SNAPSHOT")
    compileOnly("io.netty:netty-all:4.1.42.Final")
    compileOnly("com.mojang:accounts-client:1.3.0")
    compileOnly("com.mojang:authlib:1.5.21")
}

description = "ArtMap-api"
